namespace Jama.Application.Common.Interfaces;

/// <summary>Stamps "DRAFT — NOT APPROVED" onto an already-existing PDF's
/// pages. Used for a drawing's uploaded PDF, which — unlike a BOQ's — is not
/// generated by this application, so it has to be opened and marked up rather
/// than rendered with a watermark flag baked into the layout.</summary>
public interface IPdfWatermarker
{
    byte[] Stamp(byte[] pdfBytes);
}
